import React from 'react';
import { Layers, ArrowLeft } from 'lucide-react';
import { useRouter } from '../lib/router';

export const TermsView: React.FC = () => {
  const { navigate } = useRouter();

  return (
    <div className="min-h-screen bg-[#FAFAF8] px-4 py-8 text-[#171717] sm:px-6 sm:py-12 lg:px-8">
      <div className="mx-auto max-w-3xl rounded-3xl border border-[#E8E8E5] bg-[#FFFFFF] p-6 shadow-xs sm:p-10 lg:p-12">
        <div className="flex items-center justify-between pb-4 border-b border-[#F0F0EC]">
          <button type="button" aria-label="Back to Recallly home" className="flex items-center gap-2.5" onClick={() => navigate('/')}>
            <div className="w-8 h-8 rounded-xl bg-[#171717] text-[#FAFAF8] flex items-center justify-center">
              <Layers className="w-4 h-4" />
            </div>
            <span className="font-bold text-base tracking-tight">Recallly</span>
          </button>
          <button
            type="button"
            onClick={() => navigate('/')}
            className="flex items-center gap-1.5 text-sm text-[#70706B] hover:text-[#171717] font-medium"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back</span>
          </button>
        </div>

        <article aria-labelledby="terms-title" className="pt-8">
          <h1 id="terms-title" className="text-3xl font-bold tracking-tight text-[#171717]">Terms of Service</h1>
          <p className="mt-2 text-sm text-[#70706B]">Last updated: September 2026</p>

          <div className="mt-8 space-y-8 text-base leading-7 text-[#42423E]">
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">1. Acceptance of these Terms</h2><p className="mt-3">By accessing or using Recallly, you agree to these Terms of Service and the Privacy Policy. If you do not agree, do not use the service.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">2. About Recallly</h2><p className="mt-3">Recallly is a personal bookmark organization and knowledge service. It can import bookmarks from a connected X account, store and organize saved items, and provide search and other features that are available on your account.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">3. Eligibility and account responsibilities</h2><p className="mt-3">You must be legally able to agree to these Terms. Keep your account credentials secure, provide accurate information, and promptly tell us if you suspect unauthorized access. You are responsible for activity performed through your account.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">4. X connection and OAuth</h2><p className="mt-3">Recallly uses X's official OAuth flow and read-only permissions to connect an X account and access bookmarks made available through that account. Recallly does not use this connection to post, send direct messages, or obtain your X password. You can disconnect X through the available account controls. Your use of X remains subject to X's own terms and policies.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">5. Bookmark import and synchronization</h2><p className="mt-3">Recallly imports the bookmarks that X makes available through its official API. An initial import is not a promise that every historical bookmark will be available. Free accounts have manual bookmark sync. Automatic synchronization may be available for eligible Pro accounts where the feature is enabled; it is not a real-time or uninterrupted guarantee. X availability, API limits, authorization state, and provider errors can affect imports and synchronization.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">6. Your content and data</h2><p className="mt-3">You remain responsible for the bookmarks, notes, links, and other material you save or submit, including having the rights and permissions needed to use it. Recallly does not take ownership of those rights. You authorize Recallly to store and process this material as needed to provide the service, including organization, search, synchronization, and available AI features. Content originating from X or another service may remain subject to that service's terms and rights.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">7. AI-generated enrichment</h2><p className="mt-3">Recallly may use configured AI providers, including Google Gemini for current bookmark enrichment, to generate summaries, categories, topics, key concepts, and related analysis from saved text and available media. AI output can be incomplete, inaccurate, or unsuitable for your situation. Review it before relying on it; it is not professional, legal, medical, financial, or other expert advice. AI features may be unavailable, delayed, or changed.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">8. Third-party services</h2><p className="mt-3">Recallly depends on third-party services that may include Supabase for authentication and data infrastructure, X for connected bookmark access, Google Gemini for configured AI enrichment, Stripe for subscription checkout and billing management, Vercel for hosting and scheduled operations, and Resend for email features when enabled. Those services operate under their own terms and privacy practices. Their availability and policies can affect Recallly.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">9. Plans, trials, subscriptions, and billing</h2><p className="mt-3">Recallly provides a Free plan and may offer Pro features through a paid subscription. Current price, billing interval, trial eligibility, and payment terms are shown in Stripe Checkout before you confirm a purchase. The configured standard trial is 7 days when Stripe Checkout indicates that you are eligible; not every account is eligible. Stripe handles payment details and subscription billing. Renewal, cancellation, payment failure, and access timing follow the terms shown in Checkout and the billing portal. Recallly does not state a separate refund policy in these Terms.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">10. Exports and account data</h2><p className="mt-3">Authenticated users can request the JSON export provided in Recallly's data settings, which may include profile information, saved items, AI enrichment, collections, and digests. Exported or imported material can depend on the continued availability of the underlying service and source account. Recallly does not provide an in-app account deletion action through the data export control.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">11. Availability and feature changes</h2><p className="mt-3">Recallly is provided as an evolving service. We may change, suspend, or discontinue features, including features that depend on X, AI providers, hosting, or billing services. We do not promise uninterrupted availability, a particular import window, or a service level agreement.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">12. Acceptable use</h2><p className="mt-3">Do not use Recallly to break the law, violate the rights or terms of another service, access another user's account or data, bypass security or plan controls, interfere with the service, distribute malware, scrape or resell private data, or submit content that you are not permitted to use.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">13. Intellectual property</h2><p className="mt-3">Recallly's software, design, names, and service materials are owned by or licensed to the service operator and are protected by applicable law. These Terms give you a limited right to use Recallly while your access is permitted. You retain the rights you have in your own content, subject to the permissions needed for Recallly to operate.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">14. Suspension and termination</h2><p className="mt-3">You may stop using Recallly at any time. Access may be suspended or terminated where reasonably necessary for security, legal compliance, service integrity, or a material breach of these Terms. Suspension or termination does not transfer ownership of your content, but access to connected sources and service features may stop.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">15. Disclaimers</h2><p className="mt-3">To the maximum extent permitted by law, Recallly is provided on an “as available” basis. We do not guarantee that imported bookmarks will be complete, that AI output will be accurate, or that the service or any third-party dependency will be uninterrupted or error-free. Nothing in these Terms excludes a right or liability that cannot lawfully be excluded.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">16. Limitation of liability</h2><p className="mt-3">To the maximum extent permitted by law, Recallly and its service providers will not be liable for indirect, incidental, special, consequential, or exemplary losses arising from or related to use of the service. This section does not limit liability that applicable law does not permit us to limit.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">17. Changes to these Terms</h2><p className="mt-3">We may update these Terms as Recallly changes. The updated version will be posted on this page with a revised date. Your continued use of Recallly after an update means you accept the updated Terms to the extent permitted by law.</p></section>
          </div>
          <p className="mt-10 border-t border-[#F0F0EC] pt-6 text-sm leading-6 text-[#70706B]">Please also review our <a className="font-semibold text-[#171717] underline underline-offset-2" href="/privacy">Privacy Policy</a> for information about how Recallly handles personal information.</p>
        </article>
      </div>
    </div>
  );
};

export const PrivacyView: React.FC = () => {
  const { navigate } = useRouter();

  return (
    <div className="min-h-screen bg-[#FAFAF8] px-4 py-8 text-[#171717] sm:px-6 sm:py-12 lg:px-8">
      <div className="mx-auto max-w-3xl rounded-3xl border border-[#E8E8E5] bg-[#FFFFFF] p-6 shadow-xs sm:p-10 lg:p-12">
        <div className="flex items-center justify-between pb-4 border-b border-[#F0F0EC]">
          <button type="button" aria-label="Back to Recallly home" className="flex items-center gap-2.5" onClick={() => navigate('/')}>
            <div className="w-8 h-8 rounded-xl bg-[#171717] text-[#FAFAF8] flex items-center justify-center">
              <Layers className="w-4 h-4" />
            </div>
            <span className="font-bold text-base tracking-tight">Recallly</span>
          </button>
          <button
            type="button"
            onClick={() => navigate('/')}
            className="flex items-center gap-1.5 text-sm text-[#70706B] hover:text-[#171717] font-medium"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back</span>
          </button>
        </div>

        <article aria-labelledby="privacy-title" className="pt-8">
          <h1 id="privacy-title" className="text-3xl font-bold tracking-tight text-[#171717]">Privacy Policy</h1>
          <p className="mt-2 text-sm text-[#70706B]">Last updated: September 2026</p>

          <div className="mt-8 space-y-8 text-base leading-7 text-[#42423E]">
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">1. Scope</h2><p className="mt-3">This Privacy Policy explains how Recallly handles information when you visit the public site, create an account, connect X, use the Recallly application, or use its available AI, search, digest, export, and billing features.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">2. Account and authentication information</h2><p className="mt-3">When you sign up or sign in, Supabase Auth processes your authentication information. Depending on how you sign in, this can include your email address, password-related authentication records, session information, and Google sign-in information when Google authentication is enabled. Recallly stores the profile information needed to operate the account, such as display name, avatar, and timezone when provided.</p><p className="mt-3">The browser uses Supabase's supported session persistence and refresh behavior. Recallly does not ask you to provide your Supabase password to Recallly and does not expose session credentials in the application interface.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">3. X-connected information</h2><p className="mt-3">When you connect X, Recallly uses X's OAuth 2.0 flow with read-only scopes for reading tweets, users, and bookmarks, plus offline access for authorized synchronization. Recallly may receive and store the X account identifier, username, display information, avatar URL or related metadata, synchronization status, and timestamps needed to maintain the connection.</p><p className="mt-3">OAuth access and refresh tokens are encrypted and kept on the server. They are not returned through the browser's data views. Recallly does not receive your X password, post to X, send direct messages, or request unrelated write permissions.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">4. Imported bookmarks and content</h2><p className="mt-3">For bookmarks made available by X, Recallly may store the post text, post and author identifiers, author name and username, profile image reference, canonical URL, publication and import timestamps, conversation and referenced-post metadata, media metadata and permitted media URLs, language, read/favorite state, and synchronization metadata. The exact fields depend on what X returns and what remains available through its API.</p><p className="mt-3">Disconnecting X removes the stored authorization for that connection. Imported bookmarks and their Recallly enrichment remain in your library unless you remove them through an available product control. Recallly does not claim that all historical X bookmarks will always be available.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">5. AI processing</h2><p className="mt-3">Recallly can send saved bookmark text and relevant post metadata to configured AI services to provide enrichment such as summaries, categories, topics, and key concepts. When a stored image is available and the feature supports it, the text and image may be sent together for multimodal enrichment. Current bookmark enrichment uses Google Gemini.</p><p className="mt-3">AI processing is performed to provide the requested Recallly feature. AI providers may process submitted content under their own terms and policies. This Policy does not make unsupported claims about a provider's retention, training, or data-use practices; review the applicable provider information for those details. Recallly does not use this Policy to promise that AI output is accurate or that a provider will always be available.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">6. Information stored in Recallly</h2><p className="mt-3">Depending on the features you use, Recallly stores account and profile information, saved items and their enrichment, topics and categories, collections and collection membership, digest settings and generated digests, chat threads and messages, connected-account metadata, synchronization and processing jobs, subscription state, and provider usage or accounting records needed to operate and protect the service. These records are associated with the authenticated account and protected by server-side authorization and database access controls.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">7. Billing and payment information</h2><p className="mt-3">If you subscribe, Stripe processes payment details through Stripe Checkout and the billing portal. Recallly stores subscription and billing references such as Stripe customer or subscription identifiers, plan and status, billing-period dates, cancellation state, and related webhook metadata. Recallly does not receive or store your full card number through the application database.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">8. Technical data, cookies, and browser storage</h2><p className="mt-3">Recallly uses information needed to deliver and secure the service, such as request and authentication context handled by the hosting, authentication, and API infrastructure. The Supabase client persists its supported session state in browser storage so a user can remain signed in and refresh tokens. The X OAuth callback uses a short-lived, HttpOnly browser binding cookie to protect the OAuth flow. The public Interactive Demo uses a separate local-storage fixture namespace so demo interactions do not access production account data. No analytics or advertising tracker was found in the current application.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">9. How information is used</h2><ul className="mt-3 list-disc space-y-2 pl-6"><li>authenticate users and protect account access;</li><li>import, synchronize, organize, search, and display saved bookmarks;</li><li>generate available AI enrichment, digests, and related product features;</li><li>process subscriptions and provide billing management;</li><li>send configured product or digest email through Resend when enabled;</li><li>maintain, secure, troubleshoot, and improve the service; and</li><li>comply with applicable legal obligations and enforce the Terms of Service.</li></ul></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">10. Service providers and sharing</h2><p className="mt-3">Recallly shares information with service providers only as needed for the implemented service: Supabase for authentication and database infrastructure, X for OAuth and bookmark access, Google Gemini for configured AI enrichment, Stripe for checkout and subscription billing, Vercel for hosting and scheduled operations, and Resend for enabled email delivery. Providers may process information in other countries and under their own policies. Recallly does not sell your personal information or make your private library public.</p><p className="mt-3">Recallly may disclose information when reasonably necessary to comply with law, respond to valid legal process, protect users or the service, investigate abuse, or support a business transfer. The application does not provide a public endpoint for another user to read your library or enrichment.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">11. Retention</h2><p className="mt-3">Recallly does not publish a fixed retention period in the current product. Information is kept as needed to provide the features you use, maintain security and accounting records, comply with legal obligations, and resolve disputes. Disconnecting X does not by itself delete imported bookmarks. Because no self-service account-deletion workflow is currently exposed in Settings, this Policy does not promise a deletion timeline that the application does not implement.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">12. Export, deletion, and controls</h2><p className="mt-3">Authenticated users can download the JSON export offered in Settings. It can include profile information, saved items, completed AI enrichment, collections, digests, and related account data. The application also provides a confirmation-based library-clearing operation where enabled; that operation is distinct from deleting the account. Disconnecting X removes stored authorization while leaving imported library content available. No account-level deletion button is currently offered in the user interface.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">13. Security</h2><p className="mt-3">Recallly uses authenticated server requests, account-scoped access controls, database row-level policies, encrypted X OAuth tokens, and server-only provider credentials as part of its security design. No method of transmission or storage is guaranteed to be completely secure, so protect your account credentials and report suspected compromise through the contact channel Recallly makes available.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">14. International processing</h2><p className="mt-3">Recallly and its service providers may process information in countries other than where you live. The specific location and transfer mechanism can depend on the provider and deployment configuration. This Policy does not claim a particular data-residency region or contractual transfer mechanism that has not been verified.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">15. Children</h2><p className="mt-3">Recallly is not directed to children who are not legally able to agree to its Terms of Service. Do not create an account or provide personal information if you are not eligible to use the service under those Terms. Recallly does not knowingly seek personal information from children.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">16. Privacy choices and rights</h2><p className="mt-3">Depending on where you live, you may have rights over your personal information, such as access, correction, export, deletion, restriction, objection, or a right to complain to a relevant authority. The export and deletion-related controls described above are the controls currently implemented by Recallly. Any additional request instructions will be provided through the contact channel Recallly makes available.</p></section>
            <section><h2 className="text-xl font-bold leading-7 text-[#171717]">17. Changes to this Policy</h2><p className="mt-3">Recallly may update this Policy as the service or its providers change. The current version and revision date will be posted on this page. Review it periodically to understand the information practices that apply when you use Recallly.</p></section>
          </div>
          <p className="mt-10 border-t border-[#F0F0EC] pt-6 text-sm leading-6 text-[#70706B]">Please also review our <a className="font-semibold text-[#171717] underline underline-offset-2" href="/terms">Terms of Service</a>.</p>
        </article>
      </div>
    </div>
  );
};
