import React from 'react';
import { ArrowRight, CheckCircle2, Layers, Search, Sparkles } from 'lucide-react';
import { DEFAULT_TRIAL_DAYS, PLANS, X_HISTORY_EXPLANATION } from '../config/plans';
import { marketingFaqs } from '../content/marketing';

function MarketingShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#FAFAF8] text-[#171717]">
    <header className="border-b border-[#E8E8E5] bg-[#FAFAF8]/95"><div className="mx-auto flex min-h-16 max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6"><a href="/" aria-label="Find Again home" className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#171717] text-white"><Layers className="h-4 w-4" /></span><span className="font-bold tracking-tight">Find Again</span></a><nav aria-label="Public navigation" className="flex items-center gap-4 text-sm text-[#70706B]"><a href="/how-it-works" className="hidden hover:text-[#171717] sm:inline">How it works</a><a href="/pricing" className="hidden hover:text-[#171717] sm:inline">Pricing</a><a href="/blog" className="hover:text-[#171717]">Blog</a><a href="/signup" className="inline-flex items-center gap-1 rounded-xl bg-[#171717] px-3 py-2 font-semibold text-white">Get started <ArrowRight className="h-3.5 w-3.5" /></a></nav></div></header>
    {children}
    <footer className="border-t border-[#E8E8E5] px-4 py-10 text-sm text-[#70706B] sm:px-6"><div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-4"><span>Find Again · Saving something should be the beginning of its usefulness.</span><nav aria-label="Footer navigation" className="flex flex-wrap gap-4"><a href="/demo">Demo</a><a href="/faq">FAQ</a><a href="/blog">Blog</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a></nav></div></footer>
  </div>;
}

export const HowItWorksView: React.FC = () => <MarketingShell><main className="mx-auto max-w-5xl px-4 py-14 sm:px-6 sm:py-20"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#70706B]">How Find Again works</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">From saved X post to useful knowledge.</h1><p className="mt-5 text-lg leading-8 text-[#5C5C58]">Find Again imports the bookmarks X makes available, organizes them with AI-assisted enrichment, and keeps the original content readable and searchable.</p></div><section className="mt-12 grid gap-5 md:grid-cols-3" aria-label="Find Again workflow">{[
  ['1', 'Connect X securely', 'Use X OAuth with read-only bookmark and post permissions. Find Again never needs your X password and cannot post for you.'],
  ['2', 'Organize saved ideas', 'New items can receive a concise summary, one broad category, specific topics, and key concepts through the configured enrichment pipeline.'],
  ['3', 'Search and rediscover', 'Filter by category and topic, search saved content, and open the Reader without losing the original X source link.'],
].map(([number,title,text]) => <article key={number} className="rounded-3xl border border-[#E8E8E5] bg-white p-6"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#171717] text-sm font-bold text-white">{number}</span><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-3 text-base leading-7 text-[#5C5C58]">{text}</p></article>)}</section><section className="mt-14 rounded-3xl bg-[#171717] p-7 text-white sm:p-9"><h2 className="text-2xl font-bold">See the workflow with demo data.</h2><p className="mt-3 max-w-2xl text-base leading-7 text-white/70">Browse categories, topics, search, AI summaries, rich content, and the Reader without connecting an account.</p><a href="/demo" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#171717]">Explore the demo <ArrowRight className="h-4 w-4" /></a></section></main></MarketingShell>;

export const PricingView: React.FC = () => <MarketingShell><main className="mx-auto max-w-5xl px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#70706B]">Pricing</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Start free. Review Pro in checkout.</h1><p className="mt-5 text-lg leading-8 text-[#5C5C58]">Use Find Again with manual X sync for free. Stripe Checkout shows the authoritative Pro price, interval, trial eligibility, and payment terms before confirmation.</p></div><section className="mx-auto mt-12 grid max-w-4xl gap-6 md:grid-cols-2" aria-label="Find Again plans">{[
  { name:'Free', price:'$0', description:'Build and organize your X bookmark library.', features:['Connect an X account','Import recent bookmarks X makes available','Manual X bookmark sync','Search, collections, and JSON export'] },
  { name:'Find Again Pro', price:PLANS.pro.prices.monthly.formatted, description:`Eligible accounts may receive a ${DEFAULT_TRIAL_DAYS}-day trial.`, features:['AI summaries, categories, and topics','Category and topic filtering','Rich in-app bookmark Reader','Automatic sync where eligible and enabled'] },
].map((plan,index) => <article key={plan.name} className={`rounded-3xl bg-white p-7 ${index ? 'border-2 border-[#171717]' : 'border border-[#E8E8E5]'}`}><h2 className="text-xl font-bold">{plan.name}</h2><p className="mt-2 text-3xl font-bold">{plan.price}</p><p className="mt-3 text-base leading-7 text-[#5C5C58]">{plan.description}</p><ul className="mt-6 space-y-3">{plan.features.map(feature => <li key={feature} className="flex gap-2 text-sm leading-6"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-600" />{feature}</li>)}</ul><a href="/signup" className="mt-7 inline-flex w-full items-center justify-center rounded-xl bg-[#171717] px-4 py-2.5 text-sm font-semibold text-white">{index ? 'Review Pro' : 'Get started free'}</a></article>)}</section><p className="mx-auto mt-8 max-w-3xl text-center text-sm leading-6 text-[#70706B]">{X_HISTORY_EXPLANATION} Prices and subscription terms are shown by Stripe Checkout.</p></main></MarketingShell>;

export const FaqView: React.FC = () => <MarketingShell><main className="mx-auto max-w-3xl px-4 py-14 sm:px-6 sm:py-20"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#70706B]">FAQ</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Questions about Find Again.</h1><p className="mt-5 text-lg leading-8 text-[#5C5C58]">How bookmark import, AI enrichment, data controls, and billing work in the current product.</p></div><dl className="mt-12 space-y-5">{marketingFaqs.map(item => <div key={item.question} className="rounded-2xl border border-[#E8E8E5] bg-white p-5"><dt className="flex items-start gap-2 text-lg font-bold"><Search className="mt-1 h-4 w-4 shrink-0 text-indigo-600" />{item.question}</dt><dd className="mt-3 text-base leading-7 text-[#5C5C58]">{item.answer}</dd></div>)}</dl><section className="mt-12 rounded-3xl bg-indigo-50 p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Sparkles className="h-5 w-5 text-indigo-600" />Explore before connecting</h2><p className="mt-3 text-base leading-7 text-indigo-950/75">The public demo uses fixture data and does not call X, Gemini, or Stripe.</p><a href="/demo" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-950 underline underline-offset-4">Open the interactive demo <ArrowRight className="h-4 w-4" /></a></section></main></MarketingShell>;
