import { Bookmark } from '../../types';

export const demoBookmarks: Bookmark[] = [
  {
    id: 'bm_101',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901201',
    author_name: 'Andrej Karpathy',
    author_username: 'karpathy',
    author_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    content: 'A mental model for the "LLM OS":\n- CPU: LLM (orchestrates reasoning)\n- RAM: Context window (fast working memory)\n- Disk: Vector database & file system (persistent retrieval)\n- Bus: System prompts & API protocols\n- Peripherals: Tools, web browsers, compilers\n\nWe are building an entirely new computing platform layer.',
    url: 'https://x.com/karpathy/status/1789012345678901201',
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
        alt: 'LLM OS architecture diagram',
      },
    ],
    bookmark_created_at: '2026-03-12T14:20:00Z',
    imported_at: '2026-03-12T15:00:00Z',
    is_read: false,
    is_favorite: true,
    ai_summary: 'Framing modern LLM architectures as an operating system where the model acts as the CPU, context window as RAM, and external vector stores as disk storage.',
    topics: ['AI', 'Engineering'],
    keywords: ['LLM OS', 'Context Window', 'Vector DB', 'System Architecture'],
    why_saved_insight: 'Foundational mental model for designing autonomous AI agent systems with structured memory.',
    collection_ids: ['col_ai_research'],
    engagement: { likes: 38400, retweets: 6200, replies: 940 },
  },
  {
    id: 'bm_102',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901202',
    author_name: 'Andrew Ng',
    author_username: 'AndrewYNg',
    author_avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    content: 'Four agentic design patterns that drive dramatic accuracy jumps over zero-shot prompting:\n1. Reflection (self-critique before outputting)\n2. Tool use (code execution, search, APIs)\n3. Planning (multi-step decomposition)\n4. Multi-agent collaboration (specialized roles)\n\nIterative agent workflows with smaller models often beat single prompts on frontier models.',
    url: 'https://x.com/AndrewYNg/status/1789012345678901202',
    bookmark_created_at: '2026-03-11T09:15:00Z',
    imported_at: '2026-03-11T10:00:00Z',
    is_read: false,
    is_favorite: true,
    ai_summary: 'Detailed taxonomy of four core agentic design patterns: reflection, tool use, planning, and multi-agent collaboration that outperform direct single-prompt outputs.',
    topics: ['AI'],
    keywords: ['Agent Patterns', 'Reflection', 'Tool Use', 'Decomposition'],
    why_saved_insight: 'Practical blueprint for architecting resilient multi-agent software pipelines without over-relying on frontier model size.',
    collection_ids: ['col_ai_research'],
    engagement: { likes: 21900, retweets: 4300, replies: 520 },
  },
  {
    id: 'bm_103',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901203',
    author_name: 'Brian Chesky',
    author_username: 'bchesky',
    author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    content: 'Why we combined product management into product marketing and elevated designers:\nWhen product managers only manage schedules and tickets, the soul leaves the product. Designers and engineers should talk directly, obsess over craftsmanship, and ship twice a year with immense pride.',
    url: 'https://x.com/bchesky/status/1789012345678901204',
    bookmark_created_at: '2026-03-10T16:45:00Z',
    imported_at: '2026-03-10T18:00:00Z',
    is_read: true,
    is_favorite: true,
    ai_summary: 'Airbnb design-led restructuring philosophy: eliminating bureaucratic layers between design and engineering to restore product craftsmanship and shipping velocity.',
    topics: ['Product', 'Design'],
    keywords: ['Product Management', 'Design-led', 'Craftsmanship', 'Velocity'],
    why_saved_insight: 'Blueprint for lean product organization models focused on high-touch craft over bureaucratic sprint ceremonies.',
    collection_ids: ['col_design_inspo', 'col_product_strategy'],
    engagement: { likes: 19400, retweets: 3100, replies: 890 },
  },
  {
    id: 'bm_104',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901204',
    author_name: 'Shawn Wang (swyx)',
    author_username: 'swyx',
    author_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    content: 'The Rise of the AI Engineer:\nIn 2023 we proved prompt engineering is real. In 2024 we built RAG. In 2025-2026, the biggest category is applied software engineers who know how to bridge probabilistic LLM reasoning with deterministic code, evals, and streaming UX.',
    url: 'https://x.com/swyx/status/1789012345678901205',
    media: [
      {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=300&auto=format&fit=crop&q=80',
        alt: 'Code and matrix representation',
      },
    ],
    bookmark_created_at: '2026-03-09T11:00:00Z',
    imported_at: '2026-03-09T11:45:00Z',
    is_read: false,
    is_favorite: false,
    ai_summary: 'Analysis of the AI Engineer discipline: bridging non-deterministic LLM capabilities with deterministic software systems, robust evals, and low-latency UX.',
    topics: ['AI', 'Engineering'],
    keywords: ['AI Engineer', 'Evals', 'RAG', 'Streaming UX'],
    why_saved_insight: 'Defines the modern engineering stack requirements for production-ready AI applications.',
    collection_ids: ['col_ai_research'],
    engagement: { likes: 14300, retweets: 2400, replies: 310 },
  },
  {
    id: 'bm_105',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901205',
    author_name: 'Paul Graham',
    author_username: 'paulg',
    author_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    content: 'The most valuable trait in a founder is relentless resourcefulness. Running a startup is a series of seemingly insurmountable obstacles. The founders who succeed simply refuse to stop looking for ways around, over, or through them.',
    url: 'https://x.com/paulg/status/1789012345678901203',
    bookmark_created_at: '2025-11-14T18:30:00Z',
    imported_at: '2025-11-15T08:00:00Z',
    is_read: true,
    is_favorite: true,
    ai_summary: 'Core thesis on founder psychology: relentless resourcefulness in overcoming repeated roadblocks is the strongest predictor of long-term startup survival.',
    topics: ['Startups'],
    keywords: ['Founders', 'Resourcefulness', 'Mindset', 'Persistence'],
    why_saved_insight: 'Timeless perspective to revisit during challenging product and fundraising cycles.',
    collection_ids: ['col_startup_ideas'],
    engagement: { likes: 45200, retweets: 8100, replies: 1200 },
  },
  {
    id: 'bm_106',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901206',
    author_name: 'Pieter Levels',
    author_username: 'levelsio',
    author_avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    content: 'My tech stack generating $3M/yr:\n- Single index.php file\n- Vanilla JavaScript\n- SQLite\n- Ubuntu $40/mo VPS with Nginx\n\nNo build steps. No Kubernetes. No premature microservices. You don\'t need complicated tech to build high-margin software.',
    url: 'https://x.com/levelsio/status/1789012345678901206',
    bookmark_created_at: '2025-10-20T12:00:00Z',
    imported_at: '2025-10-21T07:15:00Z',
    is_read: true,
    is_favorite: true,
    ai_summary: 'Radical tech stack simplicity: building multi-million dollar solo businesses using SQLite, vanilla JS, and monolithic architecture without infrastructure overhead.',
    topics: ['Startups', 'Engineering'],
    keywords: ['Solopreneur', 'SQLite', 'Simplicity', 'Bootstrapping'],
    why_saved_insight: 'Antidote to premature infrastructure optimization. Prioritize shipping and cash flow over architectural fashion.',
    collection_ids: ['col_startup_ideas', 'col_things_to_build'],
    engagement: { likes: 52100, retweets: 7400, replies: 1980 },
  },
  {
    id: 'bm_107',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901207',
    author_name: 'Lenny Rachitsky',
    author_username: 'lennysan',
    author_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    content: 'The ultimate benchmark for product onboarding:\nIf a new user does not experience their "aha moment" within 3 to 5 minutes of signing up, 80% never return.\n\nCut your signup fields in half. Show live data immediately. Skip tutorial tooltips—let them interact directly with value.',
    url: 'https://x.com/lennysan/status/1789012345678901207',
    bookmark_created_at: '2026-03-05T15:20:00Z',
    imported_at: '2026-03-05T16:00:00Z',
    is_read: false,
    is_favorite: false,
    ai_summary: 'Product onboarding metrics: users must achieve core value within 3-5 minutes or retention drops by 80%. Prioritize instant interactivity over guided tours.',
    topics: ['Product', 'Growth'],
    keywords: ['Onboarding', 'Time-to-Value', 'Retention', 'PLG'],
    why_saved_insight: 'Checklist for refining onboarding flows: minimal forms, immediate bookmark processing, zero dead ends.',
    collection_ids: ['col_product_strategy'],
    engagement: { likes: 11200, retweets: 1850, replies: 240 },
  },
  {
    id: 'bm_108',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901208',
    author_name: 'Alex Xu',
    author_username: 'alexxubyte',
    author_avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    content: 'Caching Strategies Visualized:\n1. Cache-Aside: App reads cache, misses, queries DB, writes back.\n2. Read-Through: App treats cache as main store; cache pulls from DB.\n3. Write-Through: Cache updates DB synchronously.\n4. Write-Back: Cache queues DB updates asynchronously for peak write throughput.',
    url: 'https://x.com/alexxubyte/status/1789012345678901208',
    bookmark_created_at: '2026-01-18T10:40:00Z',
    imported_at: '2026-01-18T11:00:00Z',
    is_read: true,
    is_favorite: false,
    ai_summary: 'Comparison of distributed caching strategies (Cache-aside, Read-through, Write-through, Write-back) with tradeoffs for read-heavy vs write-heavy workloads.',
    topics: ['Engineering'],
    keywords: ['Caching', 'Distributed Systems', 'Performance', 'Write-Back'],
    why_saved_insight: 'Clear reference for designing high-performance local and edge caching layers.',
    collection_ids: [],
    engagement: { likes: 28400, retweets: 5100, replies: 410 },
  },
  {
    id: 'bm_109',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901209',
    author_name: 'Dylan Field',
    author_username: 'zoink',
    author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    content: 'The most enduring design systems are not just Figma files. They are living design tokens shared between design and code. When design tokens reflect semantic intent (e.g. background-surface vs background-elevated), dark mode and accessibility become free byproducts.',
    url: 'https://x.com/zoink/status/1789012345678901209',
    bookmark_created_at: '2026-02-28T17:10:00Z',
    imported_at: '2026-02-28T18:00:00Z',
    is_read: false,
    is_favorite: true,
    ai_summary: 'Design token architecture: using semantic tokens rather than raw hex values creates frictionless synchronization between design tools and production code.',
    topics: ['Design'],
    keywords: ['Design Tokens', 'Design Systems', 'Semantics', 'Tokens'],
    why_saved_insight: 'Guideline for maintaining clean, high-contrast, mathematically balanced interface designs.',
    collection_ids: ['col_design_inspo'],
    engagement: { likes: 16800, retweets: 2100, replies: 190 },
  },
  {
    id: 'bm_110',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901210',
    author_name: 'Harrison Chase',
    author_username: 'hwchase17',
    author_avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    content: 'Building autonomous agents is 10% prompt engineering and 90% evaluation harness.\nIf you don\'t have an automated suite of golden test cases measuring agent regression on tool calls, you cannot ship updates with confidence. Evals are the unit tests of AI software.',
    url: 'https://x.com/hwchase17/status/1789012345678901210',
    bookmark_created_at: '2026-03-12T13:30:00Z',
    imported_at: '2026-03-12T14:10:00Z',
    is_read: false,
    is_favorite: true,
    ai_summary: 'Emphasizes evaluation harnesses as the single most critical component for reliable agentic applications. Evals act as unit tests for non-deterministic AI pipelines.',
    topics: ['AI', 'Engineering'],
    keywords: ['AI Evals', 'Agent Reliability', 'Golden Datasets', 'Regression'],
    why_saved_insight: 'Crucial requirement when architecting RAG question-answering pipelines and auto-tagging workflows.',
    collection_ids: ['col_ai_research'],
    engagement: { likes: 13900, retweets: 1950, replies: 280 },
  },
  {
    id: 'bm_111',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901211',
    author_name: 'Shreyas Doshi',
    author_username: 'shreyas',
    author_avatar: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=150&auto=format&fit=crop&q=80',
    content: 'High-agency people look at constraints as variables to be altered, not fixed boundary conditions.\nWhen someone says "that\'s company policy" or "that API doesn\'t support this", the high-agency response is: "What would have to be true for this to work anyway?"',
    url: 'https://x.com/shreyas/status/1789012345678901211',
    bookmark_created_at: '2025-09-14T20:00:00Z',
    imported_at: '2025-09-15T09:00:00Z',
    is_read: true,
    is_favorite: true,
    ai_summary: 'Framework on high-agency problem solving: treating perceived constraints as malleable variables rather than immutable roadblocks.',
    topics: ['Startups', 'Product'],
    keywords: ['High Agency', 'Leadership', 'Mindset', 'Execution'],
    why_saved_insight: 'Mindset anchor for overcoming technical and organizational bottlenecks.',
    collection_ids: ['col_startup_ideas'],
    engagement: { likes: 34100, retweets: 5900, replies: 670 },
  },
  {
    id: 'bm_112',
    user_id: 'user_faruk',
    source: 'twitter',
    external_id: '1789012345678901212',
    author_name: 'Vitalik Buterin',
    author_username: 'VitalikButerin',
    author_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    content: 'The intersection of crypto and AI where decentralization actually matters:\n1. AI as a player in games/mechanisms (bots interacting on-chain with micropayments)\n2. AI as interface (agent helping users understand smart contracts)\n3. Cryptographic proofs of inference (verifying an output came from a specific weights file)',
    url: 'https://x.com/VitalikButerin/status/1789012345678901212',
    bookmark_created_at: '2026-01-30T11:15:00Z',
    imported_at: '2026-01-30T12:00:00Z',
    is_read: false,
    is_favorite: false,
    ai_summary: 'Pragmatic assessment of the AI and blockchain intersection: micropayments for autonomous agents, agentic UX for protocol interactions, and cryptographic verification of model weights.',
    topics: ['Crypto', 'AI'],
    keywords: ['Crypto AI', 'Inference Proofs', 'Agentic Payments', 'Decentralization'],
    why_saved_insight: 'Separates genuine technological synergy between blockchains and AI from speculative marketing hype.',
    collection_ids: [],
    engagement: { likes: 27500, retweets: 4800, replies: 890 },
  },
];
