import { Collection } from '../../types';

export const demoCollections: Collection[] = [
  {
    id: 'col_ai_research',
    user_id: 'user_faruk',
    name: 'AI Research',
    slug: 'ai-research',
    description: 'Research, tools and ideas about artificial intelligence, agentic architectures, and evaluation systems.',
    visibility: 'public',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-03-12T14:10:00Z',
    bookmark_ids: ['bm_101', 'bm_102', 'bm_104', 'bm_110'],
    creator_name: 'Faruk',
  },
  {
    id: 'col_startup_ideas',
    user_id: 'user_faruk',
    name: 'Startup Ideas',
    slug: 'startup-ideas',
    description: 'Interesting business ideas, opportunities, solo bootstrapping models, and founder psychology.',
    visibility: 'private',
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-03-05T15:20:00Z',
    bookmark_ids: ['bm_105', 'bm_106', 'bm_111'],
    creator_name: 'Faruk',
  },
  {
    id: 'col_product_strategy',
    user_id: 'user_faruk',
    name: 'Product Strategy',
    slug: 'product-strategy',
    description: 'Frameworks on activation metrics, customer onboarding, retention curves, and product-led growth.',
    visibility: 'private',
    created_at: '2026-02-10T12:00:00Z',
    updated_at: '2026-03-08T11:00:00Z',
    bookmark_ids: ['bm_103', 'bm_107', 'bm_111'],
    creator_name: 'Faruk',
  },
  {
    id: 'col_design_inspo',
    user_id: 'user_faruk',
    name: 'Design Inspiration',
    slug: 'design-inspiration',
    description: 'Curated perspectives on design tokens, typography, craftsmanship, and developer-designer empathy.',
    visibility: 'public',
    created_at: '2026-02-15T11:30:00Z',
    updated_at: '2026-02-28T18:00:00Z',
    bookmark_ids: ['bm_103', 'bm_109'],
    creator_name: 'Faruk',
  },
  {
    id: 'col_things_to_build',
    user_id: 'user_faruk',
    name: 'Things to Build',
    slug: 'things-to-build',
    description: 'Technical prototypes, developer tools, and lightweight utilities to build on weekends.',
    visibility: 'private',
    created_at: '2026-02-20T16:00:00Z',
    updated_at: '2026-03-01T09:00:00Z',
    bookmark_ids: ['bm_106', 'bm_108'],
    creator_name: 'Faruk',
  },
];
