import { Digest } from '../../types';

export const demoDigests: Digest[] = [
  {
    id: 'dig_sep_7_13',
    user_id: 'user_faruk',
    period_start: '2026-09-07T00:00:00Z',
    period_end: '2026-09-13T23:59:59Z',
    status: 'sent',
    title: 'Your Week in Bookmarks: Sep 7 – 13',
    bookmarks_count: 42,
    topics_count: 7,
    key_ideas_count: 6,
    topic_groups: [
      {
        topic: 'AI & Agent Infrastructure',
        summary: 'Deep dive into LLM operating systems, evaluation harnesses, and iterative agent loops with specialized sub-agents.',
        bookmark_ids: ['bm_101', 'bm_102', 'bm_104', 'bm_110'],
      },
      {
        topic: 'Product & Distribution',
        summary: 'Focus on instant time-to-value onboarding, reducing bureaucratic layers, and solo-founder capital efficiency.',
        bookmark_ids: ['bm_103', 'bm_107', 'bm_111'],
      },
      {
        topic: 'Systems & Simplicity',
        summary: 'Radical simplification in modern stacks: monolithic architectures, SQLite, and semantic design tokens.',
        bookmark_ids: ['bm_106', 'bm_108', 'bm_109'],
      },
    ],
    key_ideas: [
      'Agent infrastructure is becoming increasingly standardized around memory, tool-calling loops, and evaluation harnesses.',
      'Distribution remains the biggest challenge for many AI products—instant activation within 3 minutes dictates long-term retention.',
      'Markets are increasingly pricing longer-term AI infrastructure demand while penalizing wrapper applications with no proprietary workflow.',
      'Radical simplicity in application infrastructure often unlocks 10x shipping velocity compared to distributed microservices.',
      'Semantic design tokens turn user experience consistency into a compounding engineering advantage rather than a visual debt.',
      'High-agency founders treat organizational and technical constraints as malleable variables rather than boundary walls.',
    ],
    worth_revisiting_ids: ['bm_105', 'bm_106', 'bm_111'],
    created_at: '2026-09-14T09:00:00Z',
    sent_at: '2026-09-14T09:00:00Z',
  },
  {
    id: 'dig_aug_31_sep_6',
    user_id: 'user_faruk',
    period_start: '2026-08-31T00:00:00Z',
    period_end: '2026-09-06T23:59:59Z',
    status: 'sent',
    title: 'Your Week in Bookmarks: Aug 31 – Sep 6',
    bookmarks_count: 36,
    topics_count: 5,
    key_ideas_count: 4,
    topic_groups: [
      {
        topic: 'LLM Reasoning & Test-time Compute',
        summary: 'Investigating test-time compute scaling and multi-turn verification loops for complex reasoning.',
        bookmark_ids: ['bm_101', 'bm_102'],
      },
      {
        topic: 'Founder Psychology',
        summary: 'Persistence through market downturns and building relentless resourcefulness as a core competitive moat.',
        bookmark_ids: ['bm_105', 'bm_111'],
      },
    ],
    key_ideas: [
      'Test-time compute scaling laws are opening up new capabilities previously locked behind model parameter counts.',
      'Solo founders are leveraging AI agents to build multi-million dollar micro-conglomerates with zero headcount.',
      'Vector retrieval without semantic re-ranking leaves substantial accuracy on the table in production RAG systems.',
      'Direct customer conversation remains irreplaceable even with sophisticated quantitative telemetry.',
    ],
    worth_revisiting_ids: ['bm_103', 'bm_108'],
    created_at: '2026-09-07T09:00:00Z',
    sent_at: '2026-09-07T09:00:00Z',
  },
  {
    id: 'dig_aug_24_30',
    user_id: 'user_faruk',
    period_start: '2026-08-24T00:00:00Z',
    period_end: '2026-08-30T23:59:59Z',
    status: 'sent',
    title: 'Your Week in Bookmarks: Aug 24 – 30',
    bookmarks_count: 29,
    topics_count: 4,
    key_ideas_count: 3,
    topic_groups: [
      {
        topic: 'Architecture & Caching',
        summary: 'High throughput read-heavy workloads, write-back caching, and edge-native data consistency.',
        bookmark_ids: ['bm_108', 'bm_106'],
      },
    ],
    key_ideas: [
      'Write-back caching patterns allow solo founders to survive viral traffic spikes on cheap virtual servers.',
      'Elevating product designers into marketing roles closes the feedback gap between creation and user reception.',
      'Autonomous agent evaluation test suites prevent catastrophic regressions when updating prompt models.',
    ],
    worth_revisiting_ids: ['bm_109'],
    created_at: '2026-08-31T09:00:00Z',
    sent_at: '2026-08-31T09:00:00Z',
  },
  {
    id: 'dig_aug_17_23',
    user_id: 'user_faruk',
    period_start: '2026-08-17T00:00:00Z',
    period_end: '2026-08-23T23:59:59Z',
    status: 'sent',
    title: 'Your Week in Bookmarks: Aug 17 – 23',
    bookmarks_count: 24,
    topics_count: 4,
    key_ideas_count: 3,
    topic_groups: [
      {
        topic: 'Decentralized Networks',
        summary: 'Smart contracts, agentic micropayments, and verifiable zero-knowledge inference.',
        bookmark_ids: ['bm_112'],
      },
    ],
    key_ideas: [
      'Micropayments between autonomous agents represent the cleanest real-world utility for decentralized protocols.',
      'Design systems that export semantic CSS variables reduce frontend styling regressions to near zero.',
      'High-agency teams systematically re-frame perceived restrictions as optimization problems.',
    ],
    worth_revisiting_ids: ['bm_105'],
    created_at: '2026-08-24T09:00:00Z',
    sent_at: '2026-08-24T09:00:00Z',
  },
];
